CREATE OR REPLACE PROCEDURE dbadeec.INSERE_LOCALIZACAO(
	PDS_LOGRADOURO TEXT,
	PNR_ENDERECO TEXT,
	PDS_COMPLEMENTO TEXT,
	PDS_BAIRRO TEXT,
	PDS_CIDADE TEXT, 
	PDS_ESTADO TEXT,
	PDS_PAIS TEXT,
	PDS_CEP TEXT
)
LANGUAGE plpgsql
AS $$	 
BEGIN 
	
	INSERT INTO dbadeec.localizacao VALUES(NEXTVAL('seq_cd_localizacao'), PDS_LOGRADOURO, PNR_ENDERECO, PDS_COMPLEMENTO, PDS_BAIRRO, PDS_CIDADE, PDS_ESTADO, PDS_PAIS, PDS_CEP );
	
END $$;
